<script lang="ts">
	import PageTurn from '$lib/client/components/PageTurn.svelte';
	import SectionHeadingTopLevel from '$lib/client/components/SectionHeadingTopLevel.svelte';
	import TableOfContentsPage from '$lib/client/components/TableOfContentsPage.svelte';
	import { page } from '$app/stores';
	import AgGrid from '$lib/client/components/AgGrid.svelte';
	import { themeQuartz } from '@ag-grid-community/theming';
	import type { CarbonTheme } from 'carbon-components-svelte/src/Theme/Theme.svelte';
	import { getContext } from 'svelte';
	import type { Writable } from 'svelte/store';
	import { getHexStringFromCatppuccinColor } from '$lib/catppuccin';
	import OutboundLink from 'carbon-components-svelte/src/Link/OutboundLink.svelte';

	const licenses = [
		{
			name: '@carbon/grid',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/carbon-design-system/carbon.git',
			remoteVersion: '11.28.1',
			installedVersion: 'n/a',
			definedVersion: '^11.28.0',
			author: 'n/a',
		},
		{
			name: '@carbon/layout',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Apache-2.0',
			link: 'git+https://github.com/carbon-design-system/carbon.git',
			remoteVersion: '11.27.1',
			installedVersion: '11.24.0',
			definedVersion: '^11.24.0',
			author: 'n/a',
		},
		{
			name: '@carbon/motion',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Apache-2.0',
			link: 'git+https://github.com/carbon-design-system/carbon.git',
			remoteVersion: '11.23.1',
			installedVersion: '11.20.0',
			definedVersion: '^11.18.0',
			author: 'n/a',
		},
		{
			name: '@carbon/type',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Apache-2.0',
			link: 'git+https://github.com/carbon-design-system/carbon.git',
			remoteVersion: '11.32.1',
			installedVersion: '11.29.0',
			definedVersion: '^11.29.0',
			author: 'n/a',
		},
		{
			name: '@catppuccin/palette',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/catppuccin/palette.git',
			remoteVersion: '1.4.0',
			installedVersion: '1.2.0',
			definedVersion: '^1.2.0',
			author: 'Catppuccin Org',
		},
		{
			name: '@ibm/plex',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'OFL-1.1',
			link: 'git+https://github.com/ibm/plex.git',
			remoteVersion: '6.4.1',
			installedVersion: '6.4.1',
			definedVersion: '^6.4.1',
			author: 'n/a',
		},
		{
			name: '@octokit/core',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/octokit/core.js.git',
			remoteVersion: '6.1.2',
			installedVersion: '6.1.2',
			definedVersion: '^6.1.2',
			author: 'Gregor Martynus (https://github.com/gr2m)',
		},
		{
			name: '@octokit/webhooks',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/octokit/webhooks.js.git',
			remoteVersion: '13.3.0',
			installedVersion: '13.3.0',
			definedVersion: '^13.3.0',
			author: 'Gregor Martynus (https://twitter.com/gr2m)',
		},
		{
			name: '@octokit/webhooks-methods',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/octokit/webhooks-methods.js.git',
			remoteVersion: '5.1.0',
			installedVersion: '5.1.0',
			definedVersion: '^5.1.0',
			author: 'Gregor Martynus (https://dev.to/gr2m)',
		},
		{
			name: '@supabase/ssr',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/supabase/ssr.git',
			remoteVersion: '0.5.1',
			installedVersion: 'n/a',
			definedVersion: '^0.5.1',
			author: 'n/a',
		},
		{
			name: '@supabase/supabase-js',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/supabase/supabase-js.git',
			remoteVersion: '2.45.4',
			installedVersion: 'n/a',
			definedVersion: '^2.45.4',
			author: 'n/a',
		},
		{
			name: '@theatre/core',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Apache-2.0',
			link: 'https://github.com/AriaMinaei/theatre',
			remoteVersion: '0.7.2',
			installedVersion: '0.7.2',
			definedVersion: '^0.7.2',
			author: 'TheaterJS Oy hello@theatrejs.com https://www.theatrejs.com',
		},
		{
			name: '@theatre/studio',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'AGPL-3.0-only',
			link: 'https://github.com/AriaMinaei/theatre',
			remoteVersion: '0.7.2',
			installedVersion: '0.7.2',
			definedVersion: '^0.7.2',
			author: 'TheaterJS Oy hello@theatrejs.com https://www.theatrejs.com',
		},
		{
			name: '@threlte/core',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/threlte/threlte.git',
			remoteVersion: '7.3.1',
			installedVersion: '7.3.1',
			definedVersion: '^7.3.1',
			author: 'Grischa Erbe <hello@legrisch.com> (https://legrisch.com)',
		},
		{
			name: '@threlte/extras',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/threlte/threlte.git',
			remoteVersion: '8.12.0',
			installedVersion: '8.11.5',
			definedVersion: '^8.11.5',
			author: 'Grischa Erbe <hello@legrisch.com> (https://legrisch.com)',
		},
		{
			name: '@threlte/theatre',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/threlte/threlte.git',
			remoteVersion: '2.1.8',
			installedVersion: '2.1.8',
			definedVersion: '^2.1.8',
			author: 'Grischa Erbe <hello@legrisch.com> (https://legrisch.com)',
		},
		{
			name: '@types/three',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'https://github.com/DefinitelyTyped/DefinitelyTyped.git',
			remoteVersion: '0.169.0',
			installedVersion: 'n/a',
			definedVersion: '^0.169.0',
			author: 'n/a',
		},
		{
			name: '@xyflow/svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/xyflow/xyflow.git',
			remoteVersion: '0.1.21',
			installedVersion: 'n/a',
			definedVersion: '^0.1.21',
			author: 'n/a',
		},
		{
			name: '@zip.js/zip.js',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/gildas-lormeau/zip.js.git',
			remoteVersion: '2.7.52',
			installedVersion: 'n/a',
			definedVersion: '^2.7.52',
			author: 'n/a',
		},
		{
			name: 'alex',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/get-alex/alex.git',
			remoteVersion: '11.0.1',
			installedVersion: '11.0.1',
			definedVersion: '^11.0.1',
			author: 'Titus Wormer <tituswormer@gmail.com> (http://wooorm.com)',
		},
		{
			name: 'carbon-components',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Apache-2.0',
			link: 'git+https://github.com/carbon-design-system/carbon.git',
			remoteVersion: '11.66.1',
			installedVersion: '11.62.0',
			definedVersion: '^11.62.0',
			author: 'n/a',
		},
		{
			name: 'countries-list',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/annexare/Countries.git',
			remoteVersion: '3.1.1',
			installedVersion: '3.1.1',
			definedVersion: '^3.1.1',
			author: 'Dmytro Klymenko d@klmn.me https://github.com/dmythro',
		},
		{
			name: 'date-fns',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/date-fns/date-fns.git',
			remoteVersion: '4.1.0',
			installedVersion: 'n/a',
			definedVersion: '^4.1.0',
			author: 'n/a',
		},
		{
			name: 'driver.js',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/kamranahmedse/driver.js.git',
			remoteVersion: '1.3.1',
			installedVersion: '1.3.1',
			definedVersion: '^1.3.1',
			author: 'Kamran Ahmed <kamranahmed.se@gmail.com>',
		},
		{
			name: 'drizzle-orm',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/drizzle-team/drizzle-orm.git',
			remoteVersion: '0.35.1',
			installedVersion: 'n/a',
			definedVersion: '^0.35.1',
			author: 'n/a',
		},
		{
			name: 'ezlion',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/DorielRivalet/ezlion.git',
			remoteVersion: '7.0.0',
			installedVersion: '7.0.0',
			definedVersion: '^7.0.0',
			author: 'DorielRivalet',
		},
		{
			name: 'flag-icons',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/lipis/flag-icons.git',
			remoteVersion: '7.2.3',
			installedVersion: '7.2.3',
			definedVersion: '^7.2.3',
			author: 'Panayiotis Lipiridis <lipiridis@gmail.com>',
		},
		{
			name: 'flexsearch',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Apache-2.0',
			link: 'git+https://github.com/nextapps-de/flexsearch.git',
			remoteVersion: '0.7.43',
			installedVersion: '0.7.43',
			definedVersion: '^0.7.43',
			author: 'Thomas Wilkerling',
		},
		{
			name: 'html-to-image',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/bubkoo/html-to-image.git',
			remoteVersion: '1.11.11',
			installedVersion: '1.11.11',
			definedVersion: '^1.11.11',
			author: 'bubkooo bubkoo.wy@gmail.com',
		},
		{
			name: 'mathjs',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/josdejong/mathjs.git',
			remoteVersion: '13.2.0',
			installedVersion: 'n/a',
			definedVersion: '^13.2.0',
			author: 'n/a',
		},
		{
			name: 'mathlifier',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'https://registry.npmjs.org/mathlifier/-/mathlifier-2.0.2.tgz',
			remoteVersion: '2.0.2',
			installedVersion: 'n/a',
			definedVersion: '^2.0.2',
			author: 'n/a',
		},
		{
			name: 'mermaid',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/mermaid-js/mermaid.git',
			remoteVersion: '11.3.0',
			installedVersion: 'n/a',
			definedVersion: '^11.3.0',
			author: 'n/a',
		},
		{
			name: 'modern-screenshot',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/qq15725/modern-screenshot.git',
			remoteVersion: '4.4.39',
			installedVersion: '4.4.39',
			definedVersion: '^4.4.39',
			author: 'wxm',
		},
		{
			name: 'numbro',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/BenjaminVanRyseghem/numbro.git',
			remoteVersion: '2.5.0',
			installedVersion: '2.5.0',
			definedVersion: '^2.5.0',
			author:
				'Benjamin Van Ryseghem benjamin@vanryseghem.com https://benjamin.vanryseghem.com',
		},
		{
			name: 'postgres',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Unlicense',
			link: 'git+https://github.com/porsager/postgres.git',
			remoteVersion: '3.4.4',
			installedVersion: '3.4.4',
			definedVersion: '^3.4.4',
			author:
				'Rasmus Porsager <rasmus@porsager.com> (https://www.porsager.com)',
		},
		{
			name: 'schema-dts',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Apache-2.0',
			link: 'git+https://github.com/google/schema-dts.git',
			remoteVersion: '1.1.2',
			installedVersion: '1.1.2',
			definedVersion: '^1.1.2',
			author: 'Eyas Sharaiha <eyas@google.com> (https://eyas.sh/)',
		},
		{
			name: 'slugify',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/simov/slugify.git',
			remoteVersion: '1.6.6',
			installedVersion: '1.6.6',
			definedVersion: '^1.6.6',
			author:
				'Simeon Velichkov <simeonvelichkov@gmail.com> (https://simov.github.io)',
		},
		{
			name: 'svelte-add',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/svelte-add/svelte-add.git#main',
			remoteVersion: '2.7.3',
			installedVersion: 'n/a',
			definedVersion: '^2.7.3',
			author: 'n/a',
		},
		{
			name: 'svelte-moveable',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'https://github.com/daybrush/moveable/blob/master/packages/svelte-moveable',
			remoteVersion: '0.45.0',
			installedVersion: '0.45.0',
			definedVersion: '^0.45.0',
			author: 'Daybrush',
		},
		{
			name: 'svelte-reactions',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/Angel-Ponce/svelte-reactions.git',
			remoteVersion: '2.5.4',
			installedVersion: '2.5.4',
			definedVersion: '^2.5.4',
			author: 'Angel-Ponce',
		},
		{
			name: 'svelte-toc',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/janosh/svelte-toc.git',
			remoteVersion: '0.5.9',
			installedVersion: '0.5.9',
			definedVersion: '^0.5.9',
			author: 'Janosh Riebesell <janosh.riebesell@gmail.com>',
		},
		{
			name: 'three',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/mrdoob/three.js.git',
			remoteVersion: '0.169.0',
			installedVersion: 'n/a',
			definedVersion: '^0.169.0',
			author: 'n/a',
		},
		{
			name: 'vidstack',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'https://github.com/vidstack/player.git',
			remoteVersion: '1.12.11',
			installedVersion: 'n/a',
			definedVersion: '^1.12.11',
			author: 'n/a',
		},
		{
			name: 'xml2js',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/Leonidas-from-XIV/node-xml2js.git',
			remoteVersion: '0.6.2',
			installedVersion: '0.6.2',
			definedVersion: '^0.6.2',
			author:
				'Marek Kubica <marek@xivilization.net> (https://xivilization.net)',
		},
		{
			name: '@carbon/charts-svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/carbon-design-system/carbon-charts.git',
			remoteVersion: '1.22.0',
			installedVersion: 'n/a',
			definedVersion: '^1.22.0',
			author: 'n/a',
		},
		{
			name: '@carbon/styles',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/carbon-design-system/carbon.git',
			remoteVersion: '1.67.0',
			installedVersion: 'n/a',
			definedVersion: '^1.67.0',
			author: 'n/a',
		},
		{
			name: '@commitlint/cli',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/conventional-changelog/commitlint.git',
			remoteVersion: '19.5.0',
			installedVersion: 'n/a',
			definedVersion: '^19.5.0',
			author: 'n/a',
		},
		{
			name: '@commitlint/config-conventional',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/conventional-changelog/commitlint.git',
			remoteVersion: '19.5.0',
			installedVersion: 'n/a',
			definedVersion: '^19.5.0',
			author: 'n/a',
		},
		{
			name: '@commitlint/cz-commitlint',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/conventional-changelog/commitlint.git',
			remoteVersion: '19.5.0',
			installedVersion: 'n/a',
			definedVersion: '^19.5.0',
			author: 'n/a',
		},
		{
			name: '@neoconfetti/svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/puruvj/neoconfetti.git',
			remoteVersion: '2.2.1',
			installedVersion: '2.2.1',
			definedVersion: '^2.2.1',
			author: 'Puru Vijay',
		},
		{
			name: '@playwright/test',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/microsoft/playwright.git',
			remoteVersion: '1.48.1',
			installedVersion: 'n/a',
			definedVersion: '^1.48.1',
			author: 'n/a',
		},
		{
			name: '@release-it/conventional-changelog',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/release-it/conventional-changelog.git',
			remoteVersion: '9.0.0',
			installedVersion: 'n/a',
			definedVersion: '^9.0.0',
			author: 'n/a',
		},
		{
			name: '@rollup/plugin-typescript',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/rollup/plugins.git',
			remoteVersion: '12.1.1',
			installedVersion: 'n/a',
			definedVersion: '^12.1.1',
			author: 'n/a',
		},
		{
			name: '@sveltejs/adapter-vercel',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/sveltejs/kit.git',
			remoteVersion: '5.4.5',
			installedVersion: 'n/a',
			definedVersion: '^5.4.5',
			author: 'n/a',
		},
		{
			name: '@sveltejs/kit',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/sveltejs/kit.git',
			remoteVersion: '2.7.1',
			installedVersion: 'n/a',
			definedVersion: '^2.7.1',
			author: 'n/a',
		},
		{
			name: '@sveltejs/vite-plugin-svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/sveltejs/vite-plugin-svelte.git',
			remoteVersion: '3.1.2',
			installedVersion: 'n/a',
			definedVersion: '^3.1.2',
			author: 'n/a',
		},
		{
			name: '@types/cookie',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'https://github.com/DefinitelyTyped/DefinitelyTyped.git',
			remoteVersion: '0.6.0',
			installedVersion: '0.6.0',
			definedVersion: '^0.6.0',
			author: 'n/a',
		},
		{
			name: '@typescript-eslint/eslint-plugin',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/typescript-eslint/typescript-eslint.git',
			remoteVersion: '8.9.0',
			installedVersion: 'n/a',
			definedVersion: '^8.9.0',
			author: 'n/a',
		},
		{
			name: '@typescript-eslint/parser',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/typescript-eslint/typescript-eslint.git',
			remoteVersion: '8.9.0',
			installedVersion: 'n/a',
			definedVersion: '^8.9.0',
			author: 'n/a',
		},
		{
			name: '@vite-pwa/sveltekit',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/vite-pwa/sveltekit.git',
			remoteVersion: '0.6.5',
			installedVersion: 'n/a',
			definedVersion: '^0.6.5',
			author: 'n/a',
		},
		{
			name: 'autoprefixer',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/postcss/autoprefixer.git',
			remoteVersion: '10.4.20',
			installedVersion: '10.4.20',
			definedVersion: '^10.4.20',
			author: 'Andrey Sitnik <andrey@sitnik.ru>',
		},
		{
			name: 'carbon-components-svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/carbon-design-system/carbon-components-svelte.git',
			remoteVersion: '0.85.2',
			installedVersion: 'n/a',
			definedVersion: '^0.85.2',
			author: 'n/a',
		},
		{
			name: 'carbon-icons-svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/carbon-design-system/carbon-icons-svelte.git',
			remoteVersion: '12.12.0',
			installedVersion: 'n/a',
			definedVersion: '^12.12.0',
			author: 'n/a',
		},
		{
			name: 'carbon-pictograms-svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'Apache-2.0',
			link: 'git+https://github.com/carbon-design-system/carbon-pictograms-svelte.git',
			remoteVersion: '12.11.0',
			installedVersion: '12.11.0',
			definedVersion: '^12.11.0',
			author: 'n/a',
		},
		{
			name: 'carbon-preprocess-svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/carbon-design-system/carbon-preprocess-svelte.git',
			remoteVersion: '0.11.7',
			installedVersion: 'n/a',
			definedVersion: '^0.11.7',
			author: 'n/a',
		},
		{
			name: 'commitizen',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/commitizen/cz-cli.git',
			remoteVersion: '4.3.1',
			installedVersion: 'n/a',
			definedVersion: '^4.3.1',
			author: 'n/a',
		},
		{
			name: 'cross-env',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/kentcdodds/cross-env.git',
			remoteVersion: '7.0.3',
			installedVersion: '7.0.3',
			definedVersion: '^7.0.3',
			author: 'Kent C. Dodds <me@kentcdodds.com> (https://kentcdodds.com)',
		},
		{
			name: 'cz-conventional-changelog',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/commitizen/cz-conventional-changelog.git',
			remoteVersion: '3.3.0',
			installedVersion: '3.3.0',
			definedVersion: '^3.3.0',
			author: 'Jim Cummins <jimthedev@gmail.com>',
		},
		{
			name: 'd3',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'ISC',
			link: 'git+https://github.com/d3/d3.git',
			remoteVersion: '7.9.0',
			installedVersion: '7.9.0',
			definedVersion: '^7.9.0',
			author: 'Mike Bostock https://bost.ocks.org/mike',
		},
		{
			name: 'd3-cloud',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'BSD-3-Clause',
			link: 'git+https://github.com/jasondavies/d3-cloud.git',
			remoteVersion: '1.2.7',
			installedVersion: '1.2.7',
			definedVersion: '^1.2.7',
			author: 'Jason Davies https://www.jasondavies.com/',
		},
		{
			name: 'd3-sankey',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'BSD-3-Clause',
			link: 'git+https://github.com/d3/d3-sankey.git',
			remoteVersion: '0.12.3',
			installedVersion: '0.12.3',
			definedVersion: '^0.12.3',
			author: 'Mike Bostock https://bost.ocks.org/mike/',
		},
		{
			name: 'drizzle-kit',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/drizzle-team/drizzle-orm.git',
			remoteVersion: '0.26.2',
			installedVersion: 'n/a',
			definedVersion: '^0.26.2',
			author: 'n/a',
		},
		{
			name: 'eslint',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/eslint/eslint.git',
			remoteVersion: '9.12.0',
			installedVersion: 'n/a',
			definedVersion: '^9.12.0',
			author: 'n/a',
		},
		{
			name: 'eslint-config-prettier',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/prettier/eslint-config-prettier.git',
			remoteVersion: '9.1.0',
			installedVersion: '9.1.0',
			definedVersion: '^9.1.0',
			author: 'Simon Lydell',
		},
		{
			name: 'eslint-plugin-svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/sveltejs/eslint-plugin-svelte.git',
			remoteVersion: '2.45.1',
			installedVersion: 'n/a',
			definedVersion: '^2.45.1',
			author: 'n/a',
		},
		{
			name: 'husky',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/typicode/husky.git',
			remoteVersion: '9.1.6',
			installedVersion: 'n/a',
			definedVersion: '^9.1.6',
			author: 'n/a',
		},
		{
			name: 'mdsvex',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/pngwn/MDsveX.git',
			remoteVersion: '0.12.3',
			installedVersion: 'n/a',
			definedVersion: '^0.12.3',
			author: 'n/a',
		},
		{
			name: 'postcss',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/postcss/postcss.git',
			remoteVersion: '8.4.47',
			installedVersion: '8.4.41',
			definedVersion: '^8.4.41',
			author: 'Andrey Sitnik <andrey@sitnik.ru>',
		},
		{
			name: 'postcss-load-config',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/postcss/postcss-load-config.git',
			remoteVersion: '5.1.0',
			installedVersion: '5.1.0',
			definedVersion: '^5.1.0',
			author: 'Michael Ciniawky <michael.ciniawsky@gmail.com>',
		},
		{
			name: 'prettier',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/prettier/prettier.git',
			remoteVersion: '3.3.3',
			installedVersion: '3.3.3',
			definedVersion: '^3.3.3',
			author: 'James Long',
		},
		{
			name: 'prettier-plugin-svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/sveltejs/prettier-plugin-svelte.git',
			remoteVersion: '3.2.7',
			installedVersion: '3.2.6',
			definedVersion: '^3.2.6',
			author: 'James Birtles <jameshbirtles@gmail.com>',
		},
		{
			name: 'pug',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'https://github.com/pugjs/pug/tree/master/packages/pug',
			remoteVersion: '3.0.3',
			installedVersion: '3.0.3',
			definedVersion: '^3.0.3',
			author: 'TJ Holowaychuk <tj@vision-media.ca>',
		},
		{
			name: 'release-it',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/release-it/release-it.git',
			remoteVersion: '17.10.0',
			installedVersion: 'n/a',
			definedVersion: '^17.10.0',
			author: 'n/a',
		},
		{
			name: 'rollup-plugin-visualizer',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+ssh://git@github.com/btd/rollup-plugin-visualizer.git',
			remoteVersion: '5.12.0',
			installedVersion: '5.12.0',
			definedVersion: '^5.12.0',
			author: 'Denis Bardadym <bardadymchik@gmail.com>',
		},
		{
			name: 'sass',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/sass/dart-sass.git',
			remoteVersion: '1.80.1',
			installedVersion: '1.77.8',
			definedVersion: '^1.77.8',
			author: 'Natalie Weizenbaum nweiz@google.com https://github.com/nex3',
		},
		{
			name: 'shiki',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/shikijs/shiki.git',
			remoteVersion: '1.22.0',
			installedVersion: 'n/a',
			definedVersion: '^1.22.0',
			author: 'n/a',
		},
		{
			name: 'svelte',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/sveltejs/svelte.git',
			remoteVersion: '4.2.19',
			installedVersion: 'n/a',
			definedVersion: '^4.2.19',
			author: 'n/a',
		},
		{
			name: 'svelte-awesome-color-picker',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/Ennoriel/svelte-awesome-color-picker.git',
			remoteVersion: '3.1.4',
			installedVersion: 'n/a',
			definedVersion: '^3.1.4',
			author: 'n/a',
		},
		{
			name: 'svelte-check',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/sveltejs/language-tools.git',
			remoteVersion: '4.0.5',
			installedVersion: 'n/a',
			definedVersion: '^4.0.5',
			author: 'n/a',
		},
		{
			name: 'svelte-grid',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/vaheqelyan/svelte-grid.git',
			remoteVersion: '5.1.2',
			installedVersion: '5.1.2',
			definedVersion: '^5.1.2',
			author: 'Vahe Araqelyan <vahe.araqelyan.2013@hotmail.com>',
		},
		{
			name: 'svelte-preprocess',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/sveltejs/svelte-preprocess.git',
			remoteVersion: '6.0.3',
			installedVersion: 'n/a',
			definedVersion: '^6.0.3',
			author: 'n/a',
		},
		{
			name: 'svelte-youtube-embed',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'https://registry.npmjs.org/svelte-youtube-embed/-/svelte-youtube-embed-0.3.0.tgz',
			remoteVersion: '0.3.0',
			installedVersion: '0.3.0',
			definedVersion: '^0.3.0',
			author: 'n/a',
		},
		{
			name: 'tslib',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: '0BSD',
			link: 'git+https://github.com/Microsoft/tslib.git',
			remoteVersion: '2.8.0',
			installedVersion: '2.6.3',
			definedVersion: '^2.6.3',
			author: 'Microsoft Corp.',
		},
		{
			name: 'typescript',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/microsoft/TypeScript.git',
			remoteVersion: '5.6.3',
			installedVersion: 'n/a',
			definedVersion: '^5.6.3',
			author: 'n/a',
		},
		{
			name: 'vite',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/vitejs/vite.git',
			remoteVersion: '5.4.9',
			installedVersion: 'n/a',
			definedVersion: '^5.4.9',
			author: 'n/a',
		},
		{
			name: 'vitest',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'n/a',
			link: 'git+https://github.com/vitest-dev/vitest.git',
			remoteVersion: '2.1.3',
			installedVersion: 'n/a',
			definedVersion: '^2.1.3',
			author: 'n/a',
		},
		{
			name: 'workbox-precaching',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/googlechrome/workbox.git',
			remoteVersion: '7.1.0',
			installedVersion: '7.1.0',
			definedVersion: '^7.1.0',
			author: "Google's Web DevRel Team",
		},
		{
			name: 'workbox-recipes',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/googlechrome/workbox.git',
			remoteVersion: '7.1.0',
			installedVersion: '7.1.0',
			definedVersion: '^7.1.0',
			author: "Google's Web DevRel Team",
		},
		{
			name: 'workbox-routing',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/googlechrome/workbox.git',
			remoteVersion: '7.1.0',
			installedVersion: '7.1.0',
			definedVersion: '^7.1.0',
			author: "Google's Web DevRel Team",
		},
		{
			name: 'workbox-strategies',
			licensePeriod: 'perpetual',
			material: 'material',
			licenseType: 'MIT',
			link: 'git+https://github.com/googlechrome/workbox.git',
			remoteVersion: '7.1.0',
			installedVersion: '7.1.0',
			definedVersion: '^7.1.0',
			author: "Google's Web DevRel Team",
		},
	];

	const carbonThemeStore = getContext(
		Symbol.for('carbonTheme'),
	) as Writable<CarbonTheme>;

	// license-report
	function getAgGridTheme(theme: CarbonTheme) {
		console.log('getAgGridTheme');
		return themeQuartz.withParams({
			accentColor: getHexStringFromCatppuccinColor('blue', theme),
			backgroundColor: getHexStringFromCatppuccinColor('base', theme),
			borderColor: getHexStringFromCatppuccinColor('surface1', theme),
			browserColorScheme: theme === 'g10' ? 'light' : 'dark',
			chromeBackgroundColor: {
				ref: 'foregroundColor',
				mix: 0.07,
				onto: 'backgroundColor',
			},
			columnBorder: false,
			fontSize: '14px',
			foregroundColor: getHexStringFromCatppuccinColor('text', theme),
			headerBackgroundColor: getHexStringFromCatppuccinColor('surface0', theme),
			headerFontSize: 14,
			oddRowBackgroundColor: getHexStringFromCatppuccinColor('mantle', theme),
			rowBorder: true,
			sidePanelBorder: true,
			wrapperBorder: true,
		});
	}

	// Grid Options: Contains all of the Data Grid configurations
	let gridOptions = $derived({
		columnDefs: [
			{ field: 'name' },
			{ field: 'licensePeriod' },
			{ field: 'licenseType' },
			{ field: 'link' },
			{ field: 'remoteVersion' },
			{ field: 'installedVersion' },
			{ field: 'definedVersion' },
			{ field: 'author' },
		],
		defaultColDef: {
			flex: 1,
			minWidth: 100,
			editable: false,
			filter: true,
		},
		pagination: true,

		theme: getAgGridTheme($carbonThemeStore),
		loadThemeGoogleFonts: true,
		rowData: licenses.map((e) => {
			return {
				name: e.name,
				licensePeriod: e.licensePeriod,
				licenseType: e.licenseType,
				link: e.link,
				remoteVersion: e.remoteVersion,
				installedVersion: e.installedVersion,
				definedVersion: e.definedVersion,
				author: e.author,
			};
		}),
	});
</script>

<TableOfContentsPage displayTOC={false}>
	<div>
		<SectionHeadingTopLevel title={'Acknowledgements'} />
		<p class="spaced-paragraph">
			If you are looking for an attribution list, please also check <OutboundLink
				href="https://github.com/DorielRivalet/wycademy"
				>our README.</OutboundLink
			>
		</p>
		{#key $carbonThemeStore}
			<AgGrid {gridOptions} />
		{/key}
		<div class="page-turn">
			<PageTurn pageUrlPathName={$page.url.pathname} />
		</div>
	</div>
</TableOfContentsPage>

<style lang="scss">
	.page-turn {
		margin-top: 4rem;
	}
</style>
