# © 2023 Doriel Rivalet
# Use of this source code is governed by a MIT license that can be
# found in the LICENSE file.

header:
  license:
    spdx-id: MIT
    content: |
        © [year] [owner]
        Use of this source code is governed by a MIT license that can be
        found in the LICENSE file.
    copyright-owner: 'Doriel Rivalet'
    software-name: frontier-compendium

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - 'node_modules/'
    - '**/docs/'
    - '**/static/'
    - '.sveltekit/'
    - '.gitattributes'
    - '.gitignore'
    - '.gitkeep'
    - '.eslintignore'
    - 'CODEOWNERS'
    - '.prettierignore'
    - '.eslintignore'
    - '**/images/'
    - '.npmrc'
    - '.prettierrc'
    - '**/*.json'
    - '**/*.svg'
    - '.github/'
    - '**/*.txt'
    - '**/*.toml'
    - '**/*.adoc'
    - '**/*.svx'
		- .alexignore
		- .alexrc
		- .czrc
		- .husky/

  license-location-threshold: 80

  comment: on-failure

# If you don't want to check dependencies' license compatibility, remove the following part
dependency:
  files:
    - package.json      # If this is a npm project.
