blank_issues_enabled: true
contact_links:
  - name: "\U0001F4DA Documentation"
    url: https://github.com/DorielRivalet/wycademy/tree/main/docs/
    about: Documentation for people interested in developing and contributing to wycademy
