name: '💡 Feature Request'
description: Create a new ticket for a new feature request
title: '[REQUEST] - title'
labels: ['question', 'enhancement']
assignees:
  - DorielRivalet
body:
  - type: checkboxes
    attributes:
      label: Is there an existing feature request for this?
      description: Please search to see if a feature request already exists for the feature you are requesting.
      options:
        - label: I have searched the existing feature requests
          required: true
  - type: textarea
    id: summary
    attributes:
      label: 'Summary'
      description: Provide a brief explanation of the feature
      placeholder: Describe in a few lines your feature request
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
