name: '📜 Attribution & Intellectual Property Inquiry'
description: Submit inquiries regarding attributions, copyrights, or licensing.
title: '[IP] - title'
labels: ['IP', 'question']
assignees:
  - DorielRivalet
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reaching out regarding attributions, copyrights, or intellectual property. Please provide as much detail as possible so we can address your concern efficiently.

  - type: textarea
    id: inquiry-details
    attributes:
      label: Inquiry Details
      description: Explain your concern, including relevant links and any attributions you believe are missing.
      placeholder: Provide context about your inquiry.
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Have you reviewed our copyright page and policies?
      description: Before submitting, please check if your concern is already addressed on our [Copyright Page](https://wycademy.vercel.app/support/policies/copyright), [credits](https://github.com/DorielRivalet/wycademy/blob/main/CREDITS.md), [licenses](https://wycademy.vercel.app/support/policies/licenses) and [policies](https://github.com/DorielRivalet/wycademy/blob/main/ATTRIBUTION-POLICY.md).
      options:
        - label: Yes, I have reviewed the copyright page and policies.
          required: true

  - type: markdown
    attributes:
      value: |
        We'll review your request and respond as soon as possible. Thanks for your patience!
