/*
 * © 2023 Doriel Rivalet
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 */

// if bitfields are not needed, make an object instead.

import type {
	FrontierArmor,
	FrontierArmorSkillName,
	FrontierBowArcShot,
	FrontierBowCharge,
	FrontierBowChargeLevel,
	FrontierBowgunAttackLevel,
	FrontierBowgunRecoil,
	FrontierBowgunReloadSpeed,
	FrontierBowgunScope,
	FrontierElement,
	FrontierEquipmentRank,
	FrontierGunlanceShell,
	FrontierGunlanceShellLevel,
	FrontierHeavyBowgunUpgrade,
	FrontierHuntingHornWeaponNote,
	FrontierLightBowgunUpgrade,
	FrontierRarity,
	FrontierSigil,
	FrontierStatus,
	FrontierSwitchAxeFPhial,
	FrontierWeapon,
	FrontierWeaponClass,
	FrontierWeaponID,
	FrontierWeaponLength,
	FrontierWeaponName,
	FrontierWeaponSharpness,
	FrontierWeaponType,
	FrontierZenithSkill,
} from './types';
import GreatSwordIcon from '$lib/client/components/frontier/icon/weapon/Great_Sword_Icon_White5.svelte';
import LongSwordIcon from '$lib/client/components/frontier/icon/weapon/Long_Sword_Icon_White4.svelte';
import DualSwordsIcon from '$lib/client/components/frontier/icon/weapon/Dual_Blades_Icon_White4.svelte';
import SwordAndShieldIcon from '$lib/client/components/frontier/icon/weapon/Sword_and_Shield_Icon_White.svelte';
import GunlanceIcon from '$lib/client/components/frontier/icon/weapon/Gunlance_Icon_White4.svelte';
import LanceIcon from '$lib/client/components/frontier/icon/weapon/Lance_Icon_White5.svelte';
import HammerIcon from '$lib/client/components/frontier/icon/weapon/Hammer_Icon_White2.svelte';
import HuntingHornIcon from '$lib/client/components/frontier/icon/weapon/Hunting_Horn_Icon_White4.svelte';
import LightBowgunIcon from '$lib/client/components/frontier/icon/weapon/Light_Bowgun_Icon_White2.svelte';
import HeavyBowgunIcon from '$lib/client/components/frontier/icon/weapon/Heavy_Bowgun_Icon_White2.svelte';
import BowIcon from '$lib/client/components/frontier/icon/weapon/Bow_Icon_White4.svelte';
import TonfaIcon from '$lib/client/components/frontier/icon/weapon/Tonfa_Icon_White.svelte';
import SwitchAxeFIcon from '$lib/client/components/frontier/icon/weapon/Switch_Axe_Icon_White4.svelte';
import MagnetSpikeIcon from '$lib/client/components/frontier/icon/weapon/Magnet_Spike_Icon_White.svelte';

import ArmorHelmetIcon from '$lib/client/components/frontier/icon/armor/Helmet_Icon_White.svelte';
import ArmorChestIcon from '$lib/client/components/frontier/icon/armor/Chest_Icon_White.svelte';
import ArmorArmsIcon from '$lib/client/components/frontier/icon/armor/Arm_Icon_White.svelte';
import ArmorWaistIcon from '$lib/client/components/frontier/icon/armor/Waist_Icon_White.svelte';
import ArmorLegsIcon from '$lib/client/components/frontier/icon/armor/Leg_Icon_White.svelte';

// TODO items icons

/*
https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums
The biggest argument in favour of this format over TypeScript’s enum is that it keeps your codebase aligned with the state of JavaScript, and when/if enums are added to JavaScript then you can move to the additional syntax.
*/
export const ODirection = {
	Up: 0,
	Down: 1,
	Left: 2,
	Right: 3,
} as const;

export const Sharpness = {
	Red: 0,
	Orange: 1,
	Yellow: 2,
	Green: 3,
	Blue: 4,
	White: 5,
	Purple: 6,
	Cyan: 7,
} as const;

export const ArmorTypes: FrontierArmor[] = [
	{
		id: 0,
		name: 'Head',
		icon: ArmorHelmetIcon,
	},

	{
		id: 1,
		name: 'Chest',
		icon: ArmorChestIcon,
	},

	{
		id: 2,
		name: 'Arms',
		icon: ArmorArmsIcon,
	},

	{
		id: 3,
		name: 'Waist',
		icon: ArmorWaistIcon,
	},

	{
		id: 4,
		name: 'Legs',
		icon: ArmorLegsIcon,
	},
];

export const WeaponTypes: FrontierWeapon[] = [
	{
		id: 0,
		name: 'Great Sword',
		class: 'Blademaster',
		icon: GreatSwordIcon,
		hiden: 'Sword King',
	},
	{
		id: 1,
		name: 'Heavy Bowgun',
		class: 'Gunner',
		icon: HeavyBowgunIcon,
		hiden: 'Gun Sage',
	},
	{
		id: 2,
		name: 'Hammer',
		class: 'Blademaster',
		icon: HammerIcon,
		hiden: 'Blunt Beast',
	},
	{
		id: 3,
		name: 'Lance',
		class: 'Blademaster',
		icon: LanceIcon,
		hiden: 'Heavenly Spear',
	},
	{
		id: 4,
		name: 'Sword and Shield',
		class: 'Blademaster',
		icon: SwordAndShieldIcon,
		hiden: 'Sword Saint',
	},
	{
		id: 5,
		name: 'Light Bowgun',
		class: 'Gunner',
		icon: LightBowgunIcon,
		hiden: 'Gun Prodigy',
	},
	{
		id: 6,
		name: 'Dual Swords',
		class: 'Blademaster',
		icon: DualSwordsIcon,
		hiden: 'Dual Dragon',
	},
	{
		id: 7,
		name: 'Long Sword',
		class: 'Blademaster',
		icon: LongSwordIcon,
		hiden: 'Katana God',
	},
	{
		id: 8,
		name: 'Hunting Horn',
		class: 'Blademaster',
		icon: HuntingHornIcon,
		hiden: 'Flamboyant Emperor',
	},
	{
		id: 9,
		name: 'Gunlance',
		class: 'Blademaster',
		icon: GunlanceIcon,
		hiden: 'Cannon Emperor',
	},
	{
		id: 10,
		name: 'Bow',
		class: 'Gunner',
		icon: BowIcon,
		hiden: 'Bow Demon',
	},
	{
		id: 11,
		name: 'Tonfa',
		class: 'Blademaster',
		icon: TonfaIcon,
		hiden: 'Piercing Phoenix',
	},
	{
		id: 12,
		name: 'Switch Axe F',
		class: 'Blademaster',
		icon: SwitchAxeFIcon,
		hiden: 'Edge Marshal',
	},
	{
		id: 13,
		name: 'Magnet Spike',
		class: 'Blademaster',
		icon: MagnetSpikeIcon,
		hiden: 'Magnetic Star',
	},
];

export const SharpnessNames = Object.keys(Sharpness) as readonly string[];
export const RarityColors = [
	'#efefe9',
	'#efefe9',
	'#efefe9',
	'#73cb8d',
	'#ed93a4',
	'#96b5fd',
	'#ff985d',
	'#fffd2e',
	'#c8ff6a',
	'#68ecec',
	'#cba6fa',
	'#ff435d',
] as const;

export const ArmorSkills = [
	'',
	'Paralysis Halved',
	'Negate Paralysis',
	'Paralysis Doubled',
	'Sleep Halved',
	'Negate Sleep',
	'Sleep Doubled',
	'Stun Halved',
	'Negate Stun',
	'Stun Doubled',
	'Poison Halved',
	'Negate Poison',
	'Double Poison',
	'Deoderant',
	'Deoderant2',
	'Snowball Res',
	'Snowball Res2',
	'Sneak',
	'Taunt',
	'Health+10',
	'Health+20',
	'Health+30',
	'Health-10',
	'Health-20',
	'Health-30',
	'Recovery Speed+1',
	'Recovery Speed+2',
	'Recovery Speed-1',
	'Recovery Speed-2',
	'Razor Sharp+1',
	'Blunt Edge',
	'Sharpness+1',
	'Critical Eye+1',
	'Critical Eye+2',
	'Critical Eye+3',
	'Speed Sharpening',
	'Slothful Sharpening',
	'Guard+1',
	'Guard+2',
	'Guard-1',
	'Guard-2',
	'Auto Guard',
	'Throwing Distance UP',
	'Reload Speed+1',
	'Reload Speed+2',
	'Reload Speed+3',
	'Reload Speed-1',
	'Auto Reload',
	'Recoil Reduction+1',
	'Recoil Reduction+2',
	'Normal/Rapid UP',
	'Pierce/Pierce UP',
	'Pellet/Spread UP',
	'Normal S Lv1 Add',
	'Normal S All Add',
	'Pierce S Lv1 Add',
	// 'Pierce S Lv1&2 Add',
	'Pierce S All Add',
	'Pellet S LV1 Add',
	'Pierce S Lv1&2 Add',
	'Pellet Shot All Add',
	'Crag S Lv1 Add',
	'Crag S Lv1&Lv2 Add',
	'Crag S All Add',
	'Cluster S Lv1 Add',
	'Cluster S Lv1&Lv2 Add',
	'Cluster S All Add',
	'Status Attack Up',
	'Bomber',
	'Hunger Halved',
	'Hunger Negated',
	'Hunger Up Sm',
	'Hunger Up Lg',
	'Gourmand',
	'Scavenger',
	'Attack Up Small',
	'Attack Up Medium',
	'Attack Up Large',
	'Defense+20',
	'Defense+30',
	'Defense+60',
	'Defense-20',
	'Defense-30',
	'Defense-40',
	'Divine Protection',
	'Goddess Embrace',
	'Demonic Protection',
	'Death Gods Embrace',
	'Earplugs',
	'High Grade Earplugs',
	'Anti-Theft',
	'Wide Area+1',
	'Wide Area+2',
	'Pro Transporter',
	'All Res UP+5',
	'All Res UP+10',
	'All Res UP+20',
	'All Res-5',
	'All Res-10',
	'All Res-20',
	'Fire Res+10',
	'Fire Res+20',
	'Fire Res+30',
	'Fire Res-10',
	'Fire Res-20',
	'Fire Res-30',
	'Water Res+10',
	'Water Res+20',
	'Water Res+30',
	'Water Res-10',
	'Water Res-20',
	'Water Res-30',
	'Ice Res+10',
	'Ice Res+20',
	'Ice Res+30',
	'Ice Res-10',
	'Ice Res-20',
	'Ice Res-30',
	'Thunder Res+10',
	'Thunder Res+20',
	'Thunder Res+30',
	'Thunder Res-10',
	'Thunder Res-20',
	'Thunder Res-30',
	'Dragon Res+10',
	'Dragon Res+20',
	'Dragon Res+30',
	'Dragon Res-10',
	'Dragon Res-20',
	'Dragon Res-30',
	'Heat Halved',
	'Heat Cancel',
	'Heat Cancel2',
	'Heat Surge Small',
	'Heat Surge Large',
	'Cold Halved',
	'Cold Cancel',
	'Cold Cancel2',
	'Cold Surge Small',
	'Cold Surge Large',
	'Wind Res Small',
	'Wind Res Large',
	'Dragon Wind Breaker',
	'Map',
	'Gathering+1',
	'Gathering+2',
	'Gathering-1',
	'Gathering-2',
	'High Speed Gathering',
	'Spirits Whim',
	'Divine Whim',
	'Spectres Whim',
	'Devils Whim',
	'Good Luck',
	'Great Luck',
	'Bad Luck',
	'Horrible Luck',
	'Fishing Expert',
	'Detect',
	'Auto-tracker',
	'Recovery Items Improved',
	'Recovery Items Weakened',
	'Combination+10%',
	'Combination+15%',
	'Combination+30%',
	'Combination-5%',
	'Combination-15%',
	'Maximum Bullets',
	'Alchemy',
	'Evasion+1',
	'Evasion+2',
	'Adrenaline+1',
	'Adrenaline+2',
	'Worry',
	'Item Duration UP',
	'Item Duration DOWN',
	'Marathon Runner',
	'Short Sprinter',
	'Load UP',
	'Deviation DOWN',
	'Deviation UP',
	'Come on Big Guy',
	'Speed Eating',
	'Slow Eating',
	'Carving Expert',
	'Hazard Res Small',
	'Hazard Res Large',
	'Hazard Prone Small',
	'Hazard Prone Large',
	'Quake Res+1',
	'Vocal Chord Halved',
	'Vocal Chord Immunity',
	'BBQ Expert',
	'BBQ Master',
	'False BBQ Expert',
	'Gunnery',
	'Flute Expert',
	'Breakout',
	'Martial Arts',
	'Strong Arm+1',
	'Inspiration',
	'Passive',
	'Bond',
	'Guts',
	'Great Guts',
	'True Guts',
	'Pressure Small',
	'Capture Proficiency',
	'Poison Coatings Add',
	'Poison Coating Add',
	'Sleep Coatings Add',
	'Fire Attack Small',
	'Fire Attack Large',
	'Water Attack Small',
	'Water Attack Large',
	'Thunder Attack Small',
	'Thunder Attack Large',
	'Ice Attack Small',
	'Ice Attack Large',
	'Dragon Attack Small',
	'Dragon Attack Large',
	'Starving Wolf+1',
	'Starving Wolf+2',
	'Bomb Sword+1',
	'Bomb Sword+2',
	'Bomb Sword+3',
	'Assault Sword+1',
	'Assault Sword+2',
	'Assault Sword+3',
	'Poison Sword+1',
	'Poison Sword+2',
	'Poison Sword+3',
	'Paralysis Sword+1',
	'Paralysis Sword+2',
	'Paralysis Sword+3',
	'Sleep Sword+1',
	'Sleep Sword+2',
	'Sleep Sword+3',
	'Fire Sword+1',
	'Fire Sword+2',
	'Fire Sword+3',
	'Water Sword+1',
	'Water Sword+2',
	'Water Sword+3',
	'Ice Sword+1',
	'Ice Sword+2',
	'Ice Sword+3',
	'Thunder Sword+1',
	'Thunder Sword+2',
	'Thunder Sword+3',
	'Dragon Sword+1',
	'Dragon Sword+2',
	'Dragon Sword+3',
	'Critical Eye+4',
	'Critical Eye+5',
	'Attack Up Very Large',
	'Attack Up Absolute',
	'Super High-Grade Earplugs',
	'Peerless',
	'Precision+2',
	'Health+40',
	'Health+50',
	'Razor Sharp+2',
	'Defense+90',
	'Defense+120',
	'Summer Person',
	'Winter General',
	'Artillery Expert',
	'Artillery God',
	'Pressure Large',
	'Capture Guru',
	'Focus+2',
	'Focus+1',
	'Distraction',
	'SnS Tech 【Sword Saint】',
	'SnS Tech Kaiden',
	'SnS Tech Expert',
	'SnS Tech Novice',
	'DS Tech 【Dual Dragon】',
	'DS Tech Kaiden',
	'DS Tech Expert',
	'DS Tech Novice',
	'GS Tech 【Sword King】',
	'GS Tech Kaiden',
	'GS Tech Expert',
	'GS Tech Novice',
	'LS Tech 【Katana God】',
	'LS Tech Kaiden',
	'LS Tech Expert',
	'LS Tech Novice',
	'Hammer Tech 【Blunt Beast】',
	'Hammer Tech Kaiden',
	'Hammer Tech Expert',
	'Hammer Tech Novice',
	'HH Tech 【Flamboyant Emperor】',
	'HH Tech Kaiden',
	'HH Tech Expert',
	'HH Tech Novice',
	'Lance Tech 【Heavenly Spear】',
	'Lance Tech Kaiden',
	'Lance Tech Expert',
	'Lance Tech Novice',
	'GL Tech 【Cannon Ruler】',
	'GL Tech Kaiden',
	'GL Tech Expert',
	'GL Tech Novice',
	'HBG Tech 【Gun Sage】',
	'HBG Tech Kaiden',
	'HBG Tech Expert',
	'HBG Tech Novice',
	'LBG Tech 【Gun Prodigy】',
	'LBG Tech Kaiden',
	'LBG Tech Expert',
	'LBG Tech Novice',
	'Bow Tech 【Bow Demon】',
	'Bow Tech Kaiden',
	'Bow Tech Expert',
	'Bow Tech Novice',
	'Violent Wind Breaker',
	'Quake Res+2',
	'Trap Expert',
	'Trap Master',
	'Weapon Handling',
	'Elemental Attack Up',
	'Elemental Attack Down',
	'Stamina Rec Large',
	'Stamina Rec Small',
	'Stamina Rec Down',
	'Kickboxing King',
	'Strong Arm+2',
	'Throwing Knives+1',
	'Throwing Knives+2',
	'Caring+1',
	'Caring+2',
	'Caring+3',
	'Def Lock',
	'Fencing+1',
	'Fencing+2',
	'Status Halved',
	'Status Immunity',
	'Status Doubled',
	'SnS Tech Sword Saint2',
	'DS Tech Dual Dragon2',
	'GS Tech Sword King2',
	'LS Tech Katana God2',
	'Hammer Tech Blunt Beast2',
	'HH Tech Flamboyant Emperor2',
	'Lance Tech Heavenly Spear2',
	'GL Tech Cannon Emperor2',
	'HBG Tech Gun Sage2',
	'LBG Tech Gun Prodigy2',
	'Bow Tech Bow Demon2',
	'Passive+1',
	'Wide Area+3',
	'Wide Area-1',
	'Heavy Drinker',
	'Drunkard',
	'Crystal Res',
	'Crystal Vulnerability',
	'Magnetic Res',
	'Magnet Vulnerability',
	'Light Tread',
	'Relief',
	'Shiriagari',
	'Lone Wolf',
	'Compensation',
	'Rapid Fire',
	'Sharpening Artisan',
	'Unaffected+1',
	'Unaffected+2',
	'Unaffected+3',
	'Reflect+1',
	'Reflect+2',
	'Reflect+3',
	'Honed Blade+1',
	'Honed Blade+2',
	'Honed Blade+3',
	'Strong Attack+1',
	'Strong Attack+2',
	'Strong Attack+3',
	'Strong Attack+4',
	'Strong Attack+5',
	'Encourage+1',
	'Encourage+2',
	'Grace+1',
	'Grace+2',
	'Grace+3',
	'Vitality+1',
	'Vitality+2',
	'Vitality+3',
	'Vitality-1',
	'Wrath Awoken',
	'Buchigire',
	'Iron Arm+1',
	'Iron Arm+2',
	'Breeder',
	'unk1',
	'unk2',
	'Issen+1',
	'Issen+2',
	'Issen+3',
	'Fortify',
	'Tenacity',
	'Steady Hand+1',
	'Mounting+1',
	'Mounting+2',
	'Mounting+3',
	'Exploit Weakness',
	'Exploit Weakness2',
	'Reduce Weakness',
	'Combo Expert+1',
	'Combo Expert+2',
	'Combo Expert+3',
	'Combo Expert-1',
	'Hunter Life',
	'Hunter Valhalla',
	'Critical Shot+1',
	'Critical Shot+2',
	'Critical Shot+3',
	'Evasion+3',
	'Movement Speed UP+1',
	'Movement Speed UP+2',
	'Saving Master',
	'Saving Expert',
	'Charge Attack UP+1',
	'Charge Attack UP+2',
	'Evade Distance UP',
	'Red Soul',
	'Blue Soul',
	'Vampirism+1',
	'Vampirism+2',
	'Adaptation+1',
	'Adaptation+2',
	'Dark Finale',
	'Medical Sage',
	'Tonfa Tech 【Piercing Phoenix】',
	'Tonfa Tech Kaiden',
	'Tonfa Tech Expert',
	'Tonfa Tech Novice',
	'Tonfa Tech Large Dragon Club',
	'Incitement',
	'Blazing Majesty+1',
	'Blazing Majesty+2',
	'Drug Knowledge',
	'Absolute Defense',
	'Imperturbable',
	'Fully Prepared',
	'Negligence',
	'Extreme Collection',
	'Stylish',
	'Assistance',
	'Recoil Reduction+3',
	'Gentle Shot+1',
	'Gentle Shot+2',
	'Gentle Shot+3',
	'Elemental Exploit',
	'Elemental Diffusion',
	'Combat Supremacy',
	'Vigorous',
	'Vigorous+2',
	'Status Immunity (Myriad)',
	'Sword God+1',
	'Sword God+2',
	'Thunder Clad',
	'Status Pursuit',
	'Drawing Arts+1',
	'Drawing Arts+2',
	'Blast Resistance',
	'Flash Conversion',
	'Crit Conversion2',
	'Solid Determination',
	'Stylish Assault',
	'Freeze Res',
	'Ice Age',
	'Consumption Slayer',
	'Swaxe Tech 【Edge Marshal】',
	'Swaxe Tech Kaiden',
	'Swaxe Tech Expert',
	'Swaxe Tech Novice',
	'Swaxe Tech Great Sword General',
	'Fortification+1',
	'Fortification+2',
	'Sniper',
	'Obscurity',
	'Evasion Boost',
	'Rush',
	// 'Encourage+2',
	// 'Reflect+3',
	'Skilled',
	'Ceaseless',
	'Point Breakthrough',
	'Abnormality',
	'Spacing',
	'Strong Attack+6',
	'Sword God+3',
	'Steady Hand+2',
	'Trained+1',
	'Trained+2',
	'Furious',
	'Magspike Tech 【Magnetic Star】',
	'Magspike Tech Kaiden',
	'Magspike Tech Expert',
	'Magspike Tech Novice',
	'Magspike Tech Large Magnetic Star',
] as const;

export const ZenithSkills = [
	'',
	'Skill Slots Up+1',
	'Skill Slots Up+2',
	'Skill Slots Up+3',
	'Skill Slots Up+4',
	'Skill Slots Up+5',
	'Skill Slots Up+6',
	'Skill Slots Up+7',
	'Flash Conversion Up+1',
	'Flash Conversion Up+2',
	'Stylish Assault Up+1',
	'Stylish Assault Up+2',
	'Dissolver Up',
	'Thunder Clad Up+1',
	'Thunder Clad Up+2',
	'Ice Age Up',
	'',
	'Hearing Protection Up+1',
	'Hearing Protection Up+2',
	'Hearing Protection Up+3',
	'Wind Res Up+1',
	'Wind Res Up+2',
	'Wind Res Up+3',
	'Wind Res Up+4',
	'Quake Res Up+1',
	'Quake Res Up+2',
	'Poison Res Up+1',
	'Poison Res Up+2',
	'Para Res Up+1',
	'Para Res Up+2',
	'Sleep Res Up+1',
	'Sleep Res Up+2',
	'Vampirism Up',
	'',
	'Drug Knowledge Up',
	'Assistance Up',
	'Bullet Saver Up+1',
	'Bullet Saver Up+2',
	'Guard Up+1',
	'Guard Up+2',
	'Adaptation Up+1',
	'Adaptation Up+2',
	'Encourage Up+1',
	'Encourage Up+2',
	'Reflect Up+1',
	'Reflect Up+2',
	'Reflect Up+3',
	'Stylish Up',
	'Vigorous Up',
	'Obscurity Up',
	'Soul Up',
	'Ceaseless Up',
	'Rush Up',
] as const;

export const ArmorSkillTree = [
	'',
	'Health',
	'Recovery Speed',
	'Recovery',
	'Vampirism',
	'Herbal Science',
	'Stamina Recovery',
	'Hunger',
	'Stamina',
	'Eating',
	'Gluttony',
	'Strong Attack',
	'Attack',
	'Lone Wolf',
	'Issen',
	'Expert',
	'Flash Conversion',
	'Exploit Weakness',
	'Stylish Assault',
	'Dissolver',
	'Status Assault',
	'Drug Knowledge',
	'Status',
	'Abnormality',
	'Fire Attack',
	'Water Attack',
	'Thunder Attack',
	'Ice Attack',
	'Dragon Attack',
	'Elemental Attack',
	'Bomb Boost',
	'Gunnery',
	'Encourage',
	'Flute Expert',
	'Martial Arts',
	'Survivor',
	'Rage',
	'Adrenaline',
	'Skilled',
	'Trained',
	'Fasting',
	'Focus',
	'Charge Attack Up',
	'Weapon Handling',
	'Shiriagari',
	'Adaptation',
	'Combat Supremacy',
	'Vigorous',
	'Thunder Clad',
	'Lavish Attack',
	'Obscurity',
	'Rush',
	'Ceaseless',
	'Point Breakthrough',
	'Furious',
	'Determination',
	'Vitality',
	'Reflect',
	'Defense',
	'Fortication',
	'Guard',
	'Auto-Guard',
	'Breakout',
	'Sharpening',
	'Sharpness',
	'Stylish',
	'Edgemaster',
	'Artisan',
	'Bomb Sword',
	'Poison Sword',
	'Paralysis Sword',
	'Sleep Sword',
	'Fire Sword',
	'Water Sword',
	'Dragon Sword',
	'Thunder Sword',
	'Ice Sword',
	'Fencing',
	'Sword God',
	'Steady Hand',
	'Normal Shot Up',
	'Pierce Shot Up',
	'Pellet Shot Up',
	'Normal Shot Add',
	'Pierce Shot Add',
	'Pellet Shot Add',
	'Crag Shot Add',
	'Cluster Shot Add',
	'Poison Coating Add',
	'Paralysis Coating Add',
	'Sleep Coating Add',
	'Mounting',
	'Gentle Shot',
	'Loading',
	'Rapid Fire',
	'Auto-Reload',
	'Reload',
	'Recoil',
	'Critical Shot',
	'Precision',
	'Ammo Combiner',
	'Bullet Saver',
	'Sniper',
	'Spacing',
	'SnS Tech',
	'DS Tech',
	'LS Tech',
	'GS Tech',
	'Hammer Tech',
	'HH Tech',
	'Lance Tech',
	'GL Tech',
	'SAF Tech',
	'Tonfa Tech',
	'MS Tech',
	'HBG Tech',
	'LBG Tech',
	'Bow Tech',
	'All Res Up',
	'Fire Res',
	'Water Res',
	'Thunder Res',
	'Ice Res',
	'Dragon Res',
	'Poison Res',
	'Paralysis Res',
	'Sleep Res',
	'Status Res',
	'Stun Res',
	'Deoderant',
	'Snowball Res',
	'Vocal Chords',
	'Def Lock',
	'Drunk',
	'Blast Res',
	'Magnet Res',
	'Crystal Res',
	'Freeze Res',
	'Three Worlds Protection',
	'Hearing Protection',
	'Quake Res',
	'Wind Pressure',
	'Anti-Theft',
	'Heat Res',
	'Cold Res',
	'Light Tread',
	'Terrain',
	'Evasion Boost',
	'Evasion',
	'Evade Extender',
	'Passive',
	'Protection',
	'Guts',
	'Absolute Defense',
	'Combo Expert',
	'Everlasting',
	'Wide-Area',
	'Whim',
	'Throwing',
	'Strong Arm',
	'Ranger',
	'Cooking',
	'Fishing',
	'Combining',
	'Alchemy',
	'Speed Setup',
	'Íron Arm',
	'Knife Throwing',
	'Map',
	'Psychic',
	'Stealth',
	'Incitement',
	'Backpacking',
	'Speed Gather',
	'Gathering',
	'Carving',
	'Mindfulness',
	'Fate',
	'Pressure',
	'Monster',
	'Breeder',
	'Bond',
	'Inspiration',
	'Capture Proficiency',
	'Relief',
	'Caring',
	'Movement Speed',
	'Reinforcement',
	'Assistance',
	'Grace',
	'Compensation',
	'Dark Pulse',
	'Blazing Grace',
	'Drawing Arts',
	'Ice Age',
] as const;

export const SigilSkills = [
	'',
	'Attack Slayer',
	'Elemental Slayer',
	'Status Attack Slayer',
	'Affinity Slayer',
	'Defense Slayer',
	'Stun Value Slayer',
	'Flying Wyvern Slayer',
	'Bird Wyvern Slayer',
	'Carapaceon Slayer',
	'Piscine Slayer',
	'Fanged Beast Slayer',
	'Brute Wyvern Slayer',
	'Leviathan Slayer',
	'Elder Dragon Slayer',
	'Small Monster Slayer',
	'Elemental Coating/Crystal',
	'Hot',
	'Cold',
	'Morning',
	'Night',
	'Breeding Season',
	'Warm Season',
	'Cold Season',
	'Monday',
	'Tuesday',
	'Wednesday',
	'Thursday',
	'Friday',
	'Saturday',
	'Sunday',
	'Manager',
	'Balloon',
	'Dowsing',
	'Hunter Soul',
	'Soul Collection',
	"Gook's Friend",
	"Halk's Friend",
	'Money Expert',
	'Exp Expert',
	'Omnivore',
	'Carving Division',
	'Sleeping',
	'Decoy',
	'Spoilt',
	'Unity',
	'Aid',
	'Rapid Fire Add',
	'Ultra Rapid Fire Add',
	'Disable Rapid',
	'Heat Cannon Add',
	'Ballista Saver',
	'Raw Bow Boost',
	'Raw SnS Boost',
	'Sonic Bomb Range',
	'T.Boost(SnS)',
	'T.Boost(DS)',
	'T.Boost(GS)',
	'T.Boost(LS)',
	'T.Boost(Lance)',
	'T.Boost(GL)',
	'T.Boost(Hammer)',
	'T.Boost(HH)',
	'T.Change(SnS)',
	'T.Change(DS)',
	'T.Change(GS)',
	'T.Change(LS)',
	'T.Change(Lance)',
	'T.Change(GL)',
	'T.Change(Ham)',
	'T.Change(HH)',
	'T.Change(LBG)',
	'T.Change(HBG)',
	'T.Change(Bow)',
	'Length Up',
	// 'Shelling Change',
	'Note Change 1',
	'Note Change 2',
	'Note Change 3',
	'Arc Shot Change',
	'Rarity Change',
	'Shelling Change',
	'Tech Boost Bow',
	'Cat Breeder',
	'Shot Change',
	'Draw Strength(GS)',
	'Draw Strength(Hammer)',
	'Draw Strength(Lance)',
	'Draw Strength(SnS)',
	'Draw Strength(DS)',
	'Draw Strength(LS)',
	'Draw Strength(HH)',
	'Draw Strength(GL)',
	'Draw Strength(Tonfa)',
	'Tech Boost Tonfa',
	// 'Fanged Beast Slayer',
	'Unsheathed Movement Speed',
	'Tech Boost Swaxe',
	'Tech Boost HBG',
	'Great Sword Up',
	'Heavy Bowgun Up',
	'Hammer Up',
	'Lance Up',
	'Sword and Shield Up',
	'Light Bowgun Up',
	'Dual Swords Up',
	'Long Sword Up',
	'Hunting Horn Up',
	'Gunlance Up',
	'Bow Up',
	'Tonfa Up',
	'Swaxe Up',
	'Magspike Up',
	'Zenith Cooldown',
	'Zenith Duration',
	'Zenith Fire Res',
	'Zenith Water Res',
	'Zenith Ice Res',
	'Zenith Thunder Res',
	'Zenith Dragon Res',
	'Zenith Healing',
	'Zenith Heroics',
	'Zenith Attack',
	'Zenith Elemental',
	'Zenith Movement Speed',
	'All Zenith AOEs',
] as const;

export const HuntingHornWeaponNotesCombinations: FrontierHuntingHornWeaponNote[][] =
	[
		['White', 'Blue', 'Red'],
		['White', 'Yellow', 'Red'],
		['White', 'Green', 'Red'],
		['White', 'Cyan', 'Red'],
		['White', 'Green', 'Yellow'],
		['White', 'Blue', 'Yellow'],
		['White', 'Green', 'Cyan'],
		['White', 'Green', 'Blue'],
		['White', 'Yellow', 'Cyan'],
		['White', 'Cyan', 'Blue'],
		['Purple', 'Blue', 'Red'],
		['Purple', 'Yellow', 'Red'],
		['Purple', 'Green', 'Red'],
		['Purple', 'Cyan', 'Red'],
		['Purple', 'Green', 'Yellow'],
		['Purple', 'Blue', 'Yellow'],
		['Purple', 'Green', 'Blue'],
		['Purple', 'Green', 'Cyan'],
		['Purple', 'Yellow', 'Cyan'],
		['Purple', 'Cyan', 'Blue'],
	];

type levelQuantity = [level1: number, level2: number, level3: number];

export const defaultWeaponComponentValues = {
	weaponSharpness: [
		170, 170, 170, 170, 170, 200, 250, 350,
	] as FrontierWeaponSharpness,
	weaponName: 'Depth Flamepike "Glory"',
	weaponLevel: 100,
	weaponRarity: 12 as FrontierRarity,
	weaponTypeId: '3',
	weaponRank: 'Z' as FrontierEquipmentRank,
	weaponLength: 'Very Long' as FrontierWeaponLength,
	weaponElementBoost: true,
	weaponStatusBoost: true,
	weaponAttackBoost: true,
	weaponAttack: 100,
	weaponElementValue: 1200,
	weaponStatusValue: 1100,
	weaponElementType: 'Fire' as FrontierElement,
	weaponStatusType: 'Poison' as FrontierStatus,
	weaponZenithSkill: 'Skill Slots Up+1' as FrontierZenithSkill,
	weaponSharpnessBoost: true,
	weaponDescription:
		'A spear decorated with a rare scarlet jewel from a foreign country.',
	weaponExtraIcons: false,
	weaponType: 'Evolution' as FrontierWeaponType,
	weaponAffinity: 150,
	weaponSigil1Id: 'Attack Slayer' as FrontierSigil,
	weaponSigil2Id: 'Attack Slayer' as FrontierSigil,
	weaponSigil3Id: 'Elemental Slayer' as FrontierSigil,
	weaponSigil4Id: 'Attack Slayer' as FrontierSigil,
	weaponSigil5Id: 'Elemental Slayer' as FrontierSigil,
	weaponSigil6Id: 'Elemental Slayer' as FrontierSigil,
	weaponSigil7Id: 'Elemental Slayer' as FrontierSigil,
	weaponSigil8Id: 'Attack Slayer' as FrontierSigil,
	weaponSigil9Id: 'Elemental Slayer' as FrontierSigil,
	weaponSigil1Value: 1,
	weaponSigil2Value: -2,
	weaponSigil3Value: 3,
	weaponSigil4Value: -4,
	weaponSigil5Value: 5,
	weaponSigil6Value: -6,
	weaponSigil7Value: 7,
	weaponSigil8Value: -8,
	weaponSigil9Value: 9,
	weaponAutomaticSkill: '' as FrontierArmorSkillName,
	huntingHornNote1:
		HuntingHornWeaponNotesCombinations[0][0] as FrontierHuntingHornWeaponNote,
	huntingHornNote2:
		HuntingHornWeaponNotesCombinations[0][1] as FrontierHuntingHornWeaponNote,
	huntingHornNote3:
		HuntingHornWeaponNotesCombinations[0][2] as FrontierHuntingHornWeaponNote,
	safPhial: 'Power' as FrontierSwitchAxeFPhial,
	gunlanceShellType: 'Spread' as FrontierGunlanceShell,
	gunlanceShellLevel: 9 as FrontierGunlanceShellLevel,
	bowArc: 'Narrow' as FrontierBowArcShot,
	bowChargeType1: 'Pierce' as FrontierBowCharge,
	bowChargeLevel1: 3 as FrontierBowChargeLevel,
	bowChargeType2: 'Spread' as FrontierBowCharge,
	bowChargeLevel2: 3 as FrontierBowChargeLevel,
	bowChargeType3: 'Pierce' as FrontierBowCharge,
	bowChargeLevel3: 4 as FrontierBowChargeLevel,
	bowPoisonCoatingAvailable: true,
	bowParalysisCoatingAvailable: true,
	bowSleepCoatingAvailable: true,
	bowImpactCoatingAvailable: true,
	bowPowerCoatingAvailable: true,
	bowgunReload: 'Very Fast' as FrontierBowgunReloadSpeed,
	bowgunRecoil: 'Smaller' as FrontierBowgunRecoil,
	bowgunScope: 'Zoom' as FrontierBowgunScope,
	lightBowgunUpgrade: 'Silencer' as FrontierLightBowgunUpgrade,
	heavyBowgunUpgrade: 'Power Barrel' as FrontierHeavyBowgunUpgrade,
	bowgunAttackLevel: 5 as FrontierBowgunAttackLevel,
	bowgunNormalAmmo: [9, 9, 12] as levelQuantity,
	bowgunPierceAmmo: [6, 6, 6] as levelQuantity,
	bowgunPelletAmmo: [6, 6, 6] as levelQuantity,
	bowgunCragAmmo: [2, 2, 2] as levelQuantity,
	bowgunClusterAmmo: [0, 0, 0] as levelQuantity,
	bowgunRecoveryAmmo: [0, 0, 0] as levelQuantity,
	bowgunPoisonAmmo: [0, 0, 0] as levelQuantity,
	bowgunParalysisAmmo: [0, 0, 0] as levelQuantity,
	bowgunSleepAmmo: [0, 0, 0] as levelQuantity,
	bowgunFlamingAmmo: [6, 0, 0] as levelQuantity,
	bowgunWaterAmmo: [0, 0, 0] as levelQuantity,
	bowgunThunderAmmo: [0, 0, 0] as levelQuantity,
	bowgunFreezeAmmo: [0, 0, 0] as levelQuantity,
	bowgunDragonAmmo: [0, 0, 0] as levelQuantity,
	bowgunTranqAmmo: [2, 0, 0] as levelQuantity,
	bowgunPaintAmmo: [2, 0, 0] as levelQuantity,
	bowgunDemonAmmo: [1, 0, 0] as levelQuantity,
	bowgunArmorAmmo: [1, 0, 0] as levelQuantity,
} as const;

/*
// It requires an extra line to pull out the values
type Direction = typeof ODirection[keyof typeof ODirection];
function run(dir: Direction) {}

run(ODirection.Right);


public enum FrontierWeaponType
{
    GreatSword,
    HeavyBowgun,
    Hammer,
    Lance,
    SwordAndShield,
    LightBowgun,
    DualSwords,
    LongSword,
    HuntingHorn,
    Gunlance,
    Bow,
    Tonfa,
    SwitchAxeF,
    MagnetSpike,
}

public enum FrontierSharpness
{
    Red,
    Orange,
    Yellow,
    Green,
    Blue,
    White,
    Purple,
    Cyan,
}
*/
