/*
 * © 2023 Doriel Rivalet
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 */

// if bitfields are not needed, make an object instead.

import type {
	FrontierElement,
	FrontierEquipmentRank,
	FrontierHuntingHornWeaponNote,
	FrontierRarity,
	FrontierStatus,
	FrontierWeaponClass,
	FrontierWeaponID,
	FrontierWeaponLength,
	FrontierWeaponName,
	FrontierWeaponSharpness,
	FrontierWeaponType,
	FrontierZenithSkill,
} from './types';
import GreatSwordIcon from '$lib/client/components/frontier/icon/weapon/Great_Sword_Icon_White5.svelte';
import LongSwordIcon from '$lib/client/components/frontier/icon/weapon/Long_Sword_Icon_White4.svelte';
import DualSwordsIcon from '$lib/client/components/frontier/icon/weapon/Dual_Blades_Icon_White4.svelte';
import SwordAndShieldIcon from '$lib/client/components/frontier/icon/weapon/Sword_and_Shield_Icon_White.svelte';
import GunlanceIcon from '$lib/client/components/frontier/icon/weapon/Gunlance_Icon_White4.svelte';
import LanceIcon from '$lib/client/components/frontier/icon/weapon/Lance_Icon_White5.svelte';
import HammerIcon from '$lib/client/components/frontier/icon/weapon/Hammer_Icon_White2.svelte';
import HuntingHornIcon from '$lib/client/components/frontier/icon/weapon/Hunting_Horn_Icon_White4.svelte';
import LightBowgunIcon from '$lib/client/components/frontier/icon/weapon/Light_Bowgun_Icon_White2.svelte';
import HeavyBowgunIcon from '$lib/client/components/frontier/icon/weapon/Heavy_Bowgun_Icon_White2.svelte';
import BowIcon from '$lib/client/components/frontier/icon/weapon/Bow_Icon_White4.svelte';
import TonfaIcon from '$lib/client/components/frontier/icon/weapon/Tonfa_Icon_White.svelte';
import SwitchAxeFIcon from '$lib/client/components/frontier/icon/weapon/Switch_Axe_Icon_White4.svelte';
import MagnetSpikeIcon from '$lib/client/components/frontier/icon/weapon/Magnet_Spike_Icon_White.svelte';

/*
https://www.typescriptlang.org/docs/handbook/enums.html#objects-vs-enums
The biggest argument in favour of this format over TypeScript’s enum is that it keeps your codebase aligned with the state of JavaScript, and when/if enums are added to JavaScript then you can move to the additional syntax.
*/
export const ODirection = {
	Up: 0,
	Down: 1,
	Left: 2,
	Right: 3,
} as const;

export const Sharpness = {
	Red: 0,
	Orange: 1,
	Yellow: 2,
	Green: 3,
	Blue: 4,
	White: 5,
	Purple: 6,
	Cyan: 7,
} as const;

export const WeaponTypes = [
	{
		id: 0 as FrontierWeaponID,
		name: 'Great Sword' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: GreatSwordIcon,
		hiden: 'Sword King',
	},
	{
		id: 1 as FrontierWeaponID,
		name: 'Heavy Bowgun' as FrontierWeaponName,
		class: 'Gunner' as FrontierWeaponClass,
		icon: HeavyBowgunIcon,
		hiden: 'Gun Sage',
	},
	{
		id: 2 as FrontierWeaponID,
		name: 'Hammer' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: HammerIcon,
		hiden: 'Blunt Beast',
	},
	{
		id: 3 as FrontierWeaponID,
		name: 'Lance' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: LanceIcon,
		hiden: 'Heavenly Spear',
	},
	{
		id: 4 as FrontierWeaponID,
		name: 'Sword and Shield' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: SwordAndShieldIcon,
		hiden: 'Sword Saint',
	},
	{
		id: 5 as FrontierWeaponID,
		name: 'Light Bowgun' as FrontierWeaponName,
		class: 'Gunner' as FrontierWeaponClass,
		icon: LightBowgunIcon,
		hiden: 'Gun Prodigy',
	},
	{
		id: 6 as FrontierWeaponID,
		name: 'Dual Swords' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: DualSwordsIcon,
		hiden: 'Dual Dragon',
	},
	{
		id: 7 as FrontierWeaponID,
		name: 'Long Sword' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: LongSwordIcon,
		hiden: 'Katana God',
	},
	{
		id: 8 as FrontierWeaponID,
		name: 'Hunting Horn' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: HuntingHornIcon,
		hiden: 'Flamboyant Emperor',
	},
	{
		id: 9 as FrontierWeaponID,
		name: 'Gunlance' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: GunlanceIcon,
		hiden: 'Cannon Emperor',
	},
	{
		id: 10 as FrontierWeaponID,
		name: 'Bow' as FrontierWeaponName,
		class: 'Gunner' as FrontierWeaponClass,
		icon: BowIcon,
		hiden: 'Bow Demon',
	},
	{
		id: 11 as FrontierWeaponID,
		name: 'Tonfa' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: TonfaIcon,
		hiden: 'Piercing Phoenix',
	},
	{
		id: 12 as FrontierWeaponID,
		name: 'Switch Axe F' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: SwitchAxeFIcon,
		hiden: 'Edge Marshal',
	},
	{
		id: 13 as FrontierWeaponID,
		name: 'Magnet Spike' as FrontierWeaponName,
		class: 'Blademaster' as FrontierWeaponClass,
		icon: MagnetSpikeIcon,
		hiden: 'Magnetic Star',
	},
] as const;

export const SharpnessNames = Object.keys(Sharpness) as readonly string[];
export const RarityColors = [
	'#efefe9',
	'#efefe9',
	'#efefe9',
	'#73cb8d',
	'#ed93a4',
	'#96b5fd',
	'#ff985d',
	'#fffd2e',
	'#c8ff6a',
	'#68ecec',
	'#cba6fa',
	'#ff435d',
] as const;

export const ZenithSkills = [
	'',
	'Skill Slots Up+1',
	'Skill Slots Up+2',
	'Skill Slots Up+3',
	'Skill Slots Up+4',
	'Skill Slots Up+5',
	'Skill Slots Up+6',
	'Skill Slots Up+7',
	'Flash Conversion Up+1',
	'Flash Conversion Up+2',
	'Stylish Assault Up+1',
	'Stylish Assault Up+2',
	'Dissolver Up',
	'Thunder Clad Up+1',
	'Thunder Clad Up+2',
	'Ice Age Up',
	'',
	'Hearing Protection Up+1',
	'Hearing Protection Up+2',
	'Hearing Protection Up+3',
	'Wind Res Up+1',
	'Wind Res Up+2',
	'Wind Res Up+3',
	'Wind Res Up+4',
	'Quake Res Up+1',
	'Quake Res Up+2',
	'Poison Res Up+1',
	'Poison Res Up+2',
	'Para Res Up+1',
	'Para Res Up+2',
	'Sleep Res Up+1',
	'Sleep Res Up+2',
	'Vampirism Up',
	'',
	'Drug Knowledge Up',
	'Assistance Up',
	'Bullet Saver Up+1',
	'Bullet Saver Up+2',
	'Guard Up+1',
	'Guard Up+2',
	'Adaptation Up+1',
	'Adaptation Up+2',
	'Encourage Up+1',
	'Encourage Up+2',
	'Reflect Up+1',
	'Reflect Up+2',
	'Reflect Up+3',
	'Stylish Up',
	'Vigorous Up',
	'Obscurity Up',
	'Soul Up',
	'Ceaseless Up',
	'Rush Up',
] as const;

export const SigilSkills = [
	'',
	'Attack Slayer',
	'Elemental Slayer',
	'Status Attack Slayer',
	'Affinity Slayer',
	'Defense Slayer',
	'Stun Value Slayer',
	'Flying Wyvern Slayer',
	'Bird Wyvern Slayer',
	'Carapaceon Slayer',
	'Piscine Slayer',
	'Fanged Beast Slayer',
	'Brute Wyvern Slayer',
	'Leviathan Slayer',
	'Elder Dragon Slayer',
	'Small Monster Slayer',
	'Elemental Coating/Crystal',
	'Hot',
	'Cold',
	'Morning',
	'Night',
	'Breeding Season',
	'Warm Season',
	'Cold Season',
	'Monday',
	'Tuesday',
	'Wednesday',
	'Thursday',
	'Friday',
	'Saturday',
	'Sunday',
	'Manager',
	'Balloon',
	'Dowsing',
	'Hunter Soul',
	'Soul Collection',
	"Gook's Friend",
	"Halk's Friend",
	'Money Expert',
	'Exp Expert',
	'Omnivore',
	'Carving Division',
	'Sleeping',
	'Decoy',
	'Spoilt',
	'Unity',
	'Aid',
	'Rapid Fire Add',
	'Ultra Rapid Fire Add',
	'Disable Rapid',
	'Heat Cannon Add',
	'Ballista Saver',
	'Raw Bow Boost',
	'Raw SnS Boost',
	'Sonic Bomb Range',
	'T.Boost(SnS)',
	'T.Boost(DS)',
	'T.Boost(GS)',
	'T.Boost(LS)',
	'T.Boost(Lance)',
	'T.Boost(GL)',
	'T.Boost(Hammer)',
	'T.Boost(HH)',
	'T.Change(SnS)',
	'T.Change(DS)',
	'T.Change(GS)',
	'T.Change(LS)',
	'T.Change(Lance)',
	'T.Change(GL)',
	'T.Change(Ham)',
	'T.Change(HH)',
	'T.Change(LBG)',
	'T.Change(HBG)',
	'T.Change(Bow)',
	'Length Up',
	// 'Shelling Change',
	'Note Change 1',
	'Note Change 2',
	'Note Change 3',
	'Arc Shot Change',
	'Rarity Change',
	'Shelling Change',
	'Tech Boost Bow',
	'Cat Breeder',
	'Shot Change',
	'Draw Strength(GS)',
	'Draw Strength(Hammer)',
	'Draw Strength(Lance)',
	'Draw Strength(SnS)',
	'Draw Strength(DS)',
	'Draw Strength(LS)',
	'Draw Strength(HH)',
	'Draw Strength(GL)',
	'Draw Strength(Tonfa)',
	'Tech Boost Tonfa',
	// 'Fanged Beast Slayer',
	'Unsheathed Movement Speed',
	'Tech Boost Swaxe',
	'Tech Boost HBG',
	'Great Sword Up',
	'Heavy Bowgun Up',
	'Hammer Up',
	'Lance Up',
	'Sword and Shield Up',
	'Light Bowgun Up',
	'Dual Swords Up',
	'Long Sword Up',
	'Hunting Horn Up',
	'Gunlance Up',
	'Bow Up',
	'Tonfa Up',
	'Swaxe Up',
	'Magspike Up',
	'Zenith Cooldown',
	'Zenith Duration',
	'Zenith Fire Res',
	'Zenith Water Res',
	'Zenith Ice Res',
	'Zenith Thunder Res',
	'Zenith Dragon Res',
	'Zenith Healing',
	'Zenith Heroics',
	'Zenith Attack',
	'Zenith Elemental',
	'Zenith Movement Speed',
	'All Zenith AOEs',
] as const;

export const HuntingHornWeaponNotesCombinations: FrontierHuntingHornWeaponNote[][] =
	[
		['White', 'Blue', 'Red'],
		['White', 'Yellow', 'Red'],
		['White', 'Green', 'Red'],
		['White', 'Cyan', 'Red'],
		['White', 'Green', 'Yellow'],
		['White', 'Blue', 'Yellow'],
		['White', 'Green', 'Cyan'],
		['White', 'Green', 'Blue'],
		['White', 'Yellow', 'Cyan'],
		['White', 'Cyan', 'Blue'],
		['Purple', 'Blue', 'Red'],
		['Purple', 'Yellow', 'Red'],
		['Purple', 'Green', 'Red'],
		['Purple', 'Cyan', 'Red'],
		['Purple', 'Green', 'Yellow'],
		['Purple', 'Blue', 'Yellow'],
		['Purple', 'Green', 'Blue'],
		['Purple', 'Green', 'Cyan'],
		['Purple', 'Yellow', 'Cyan'],
		['Purple', 'Cyan', 'Blue'],
	];

export const defaultWeaponComponentValues = {
	weaponSharpness: [
		170, 170, 170, 170, 170, 200, 250, 350,
	] as FrontierWeaponSharpness,
	weaponName: 'Depth Flamepike "Glory"',
	weaponLevel: 100,
	weaponRarity: 12 as FrontierRarity,
	weaponTypeId: '3',
	weaponRank: 'Z' as FrontierEquipmentRank,
	weaponLength: 'Very Long' as FrontierWeaponLength,
	weaponElementBoost: true,
	weaponStatusBoost: true,
	weaponAttackBoost: true,
	weaponAttack: 100,
	weaponElementValue: 1200,
	weaponStatusValue: 1100,
	weaponElementType: 'Fire' as FrontierElement,
	weaponStatusType: 'Poison' as FrontierStatus,
	weaponZenithSkill: 'Skill Slots Up+1' as FrontierZenithSkill,
	weaponSharpnessBoost: true,
	weaponDescription:
		'A spear decorated with a rare scarlet jewel from a foreign country.',
	weaponExtraIcons: false,
	weaponType: 'Evolution' as FrontierWeaponType,
	weaponAffinity: 150,
	weaponSigil1Id: 'Attack Slayer',
	weaponSigil2Id: 'Attack Slayer',
	weaponSigil3Id: 'Elemental Slayer',
	weaponSigil4Id: 'Attack Slayer',
	weaponSigil5Id: 'Elemental Slayer',
	weaponSigil6Id: 'Elemental Slayer',
	weaponSigil7Id: 'Elemental Slayer',
	weaponSigil8Id: 'Attack Slayer',
	weaponSigil9Id: 'Elemental Slayer',
	weaponSigil1Value: 1,
	weaponSigil2Value: -2,
	weaponSigil3Value: 3,
	weaponSigil4Value: -4,
	weaponSigil5Value: 5,
	weaponSigil6Value: -6,
	weaponSigil7Value: 7,
	weaponSigil8Value: -8,
	weaponSigil9Value: 9,
} as const;

/*
// It requires an extra line to pull out the values
type Direction = typeof ODirection[keyof typeof ODirection];
function run(dir: Direction) {}

run(ODirection.Right);


public enum FrontierWeaponType
{
    GreatSword,
    HeavyBowgun,
    Hammer,
    Lance,
    SwordAndShield,
    LightBowgun,
    DualSwords,
    LongSword,
    HuntingHorn,
    Gunlance,
    Bow,
    Tonfa,
    SwitchAxeF,
    MagnetSpike,
}

public enum FrontierSharpness
{
    Red,
    Orange,
    Yellow,
    Green,
    Blue,
    White,
    Purple,
    Cyan,
}
*/
