export const frontierColorNames = [
  { var: "--fz-sharpness-red", name: "Red Sharpness",},
  { var: "--fz-sharpness-orange", name: "Orange Sharpness",},
  { var: "--fz-sharpness-yellow", name: "Yellow Sharpness",},
  { var: "--fz-sharpness-green", name: "Green Sharpness",},
  { var: "--fz-sharpness-blue", name: "Blue Sharpness",},
  { var: "--fz-sharpness-white", name: "White Sharpness",},
  { var: "--fz-sharpness-purple", name: "Purple Sharpness",},
  { var: "--fz-sharpness-cyan", name: "Cyan Sharpness",},
  { var: "--fz-rare-1-3", name: "Rare 1-3",},
  { var: "--fz-rare-4", name: "Rare 4",},
  { var: "--fz-rare-5", name: "Rare 5",},
  { var: "--fz-rare-6", name: "Rare 6",},
  { var:  "--fz-rare-7", name: "Rare 7",},
  { var: "--fz-rare-8", name: "Rare 8",},
  { var: "--fz-rare-9", name: "Rare 9",},
  { var: "--fz-rare-10", name: "Rare 10",},
  { var: "--fz-rare-11", name: "Rare 11",},
  { var: "--fz-rare-12", name: "Rare 12",},
];