name: Github Status
on: push

jobs:
  github-status:
    runs-on: ubuntu-latest
    steps:
      - name: Check GitHub Status
        uses: crazy-max/ghaction-github-status@v4
        with:
          overall_threshold: minor
          pages_threshold: partial_outage
      - name: Checkout
        uses: actions/checkout@v4
