name: Check Package License Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  check-license-changes:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Checkout base branch for comparison
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base-branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0' # from .nvmrc

      - name: Install dependencies
        run: npm ci

      - name: Install license-report
        run: npm install -g license-report

      - name: Generate license reports
        run: |
          license-report --output=json --fields=name --fields=licenseType > pr-licenses.json
          cd base-branch
          npm ci
          license-report --output=json --fields=name --fields=licenseType > base-licenses.json
          mv base-licenses.json ..

      - name: Compare licenses
        run: node scripts/compare-licenses.js
