name: Check Package License Changes

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'package.json'
      - 'package-lock.json'

jobs:
  check-license-changes:
    runs-on: ubuntu-latest
    # Only run on Dependabot PRs
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4

      - name: Checkout base branch for comparison
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}
          path: base-branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install license-report
        run: npm install -g license-report

      - name: Generate license report for PR branch
        run: |
          license-report --output=json --fields=name --fields=licenseType --fields=installedVersion > pr-licenses.json

      - name: Generate license report for base branch
        run: |
          cd base-branch
          license-report --output=json --fields=name --fields=licenseType --fields=installedVersion > ../base-licenses.json

      - name: Compare licenses and check for changes
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');

            // Read license files
            const baseLicenses = JSON.parse(fs.readFileSync('base-licenses.json', 'utf8'));
            const prLicenses = JSON.parse(fs.readFileSync('pr-licenses.json', 'utf8'));

            // Get PR details to determine which package is being updated
            const prTitle = context.payload.pull_request.title;
            let updatedPackageMatch = prTitle.match(/bump ([@\w\/-]+) from ([\d\.]+) to ([\d\.]+)/i);

            if (!updatedPackageMatch) {
              console.log("This doesn't appear to be a standard Dependabot version bump PR");
              return;
            }

            const packageName = updatedPackageMatch[1];
            const oldVersion = updatedPackageMatch[2];
            const newVersion = updatedPackageMatch[3];

            console.log(`Checking license changes for ${packageName} from v${oldVersion} to v${newVersion}`);

            // Find the package in both license reports
            const oldPackageData = baseLicenses.find(pkg => pkg.name === packageName);
            const newPackageData = prLicenses.find(pkg => pkg.name === packageName);

            if (!oldPackageData) {
              console.log(`Could not find old package version (${packageName}) in base license report`);
              console.log("Available packages in base:", baseLicenses.map(pkg => pkg.name).join(", "));
            }

            if (!newPackageData) {
              console.log(`Could not find new package version (${packageName}) in PR license report`);
              console.log("Available packages in PR:", prLicenses.map(pkg => pkg.name).join(", "));
            }

            if (!oldPackageData || !newPackageData) {
              console.log("Package not found in one or both reports, cannot compare licenses");
              return;
            }

            const oldLicense = oldPackageData.licenseType;
            const newLicense = newPackageData.licenseType;

            console.log(`Previous license for ${packageName}@${oldVersion}: ${oldLicense}`);
            console.log(`New license for ${packageName}@${newVersion}: ${newLicense}`);

            // Check if license changed
            if (oldLicense !== newLicense) {
              console.log(`⚠️ LICENSE CHANGE DETECTED: ${oldLicense} → ${newLicense}`);
              core.setFailed(`License change detected for ${packageName}: ${oldLicense} → ${newLicense}`);

              // Add a comment to the PR with details about the license change
              const { owner, repo } = context.repo;
              const issue_number = context.payload.pull_request.number;

              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number,
                body: `⚠️ **License Change Detected**\n\nPackage \`${packageName}\` has changed license:\n- Previous: \`${oldLicense}\`\n- New: \`${newLicense}\`\n\nPlease review this change to ensure it complies with your organization's licensing policies.`
              });
            } else {
              console.log("✅ No license changes detected");
            }
